feat: add support for node-gyp --jobs option to parallelize an indivi…
electron/rebuild pull request #1106
Opened 2023-10-01 20:58 UTC by nkallen

Hi,

I have a native module with a couple hundred c++ files. Electron-rebuild does have a "parallel" option but this doesn't actually run make in parallel WITHIN one module. This adds support for node-gyp's --jobs option, so that users like me can run electron-rebuild --jobs=max from the command line

Thanks

2023-10-12 08:01 UTC, nkallen commented
Hi,

Are you guys not accepting submissions? I'm pretty
Sure this is a useful feature for everyone

2023-10-12 08:17 UTC, BlackHole1 approved these changes
LGTM. Although it can be achieved through the [JOBS environment variable](https://github.com/nodejs/node-gyp/blob/b3d41aeb737ddd54cc292f363abc561dcc0a614e/lib/build.js#L27) in node-gyp, I personally feel that supporting the `--jobs` parameter would be better. Thank you for your contribution!

PTAL @dsanders11

2023-11-07 21:35 UTC, erickzhao commented
ref https://github.com/electron/rebuild/issues/303

2023-11-07 21:38 UTC, dsanders11 commented
References #303.

2023-11-07 21:39 UTC, erickzhao approved these changes
Small docs change, but LGTM

2023-11-07 21:39 UTC, erickzhao commented on README.md
> +  -j, --jobs                   Run make in parallel. The value max will use all available CPU cores
```suggestion
  -j, --jobs                   Run make in parallel. The value max will use all available CPU cores. Defaults to 1.
```

2023-11-07 21:39 UTC, erickzhao commented on src/cli.ts
> +  jobs: {alias: 'j', type: 'string', description: 'Run make in parallel. The value max will use all available CPU cores'},
```suggestion
  jobs: {alias: 'j', type: 'string', description: 'Run make in parallel. The value max will use all available CPU cores. Defaults to 1.'},
```

2023-11-10 23:26 UTC, dsanders11 requested changes
I think this may be currently possible by setting the `npm_config_jobs` environment variable, [see the `node-gyp` documentation](https://github.com/nodejs/node-gyp#environment-variables).

@nkallen, could you test using the environment variable to change the number of jobs and see if that works for your use case? If it does, I'd rather document in this repo that you can pass additional options to `node-gyp` in this manner, rather than plumbing in through. Someone may come along with the need for another `node-gyp` option, like `--python`, and plumbing them through on a case-by-case basis doesn't seem ideal if they're easy to set via environment variables.

2026-08-19 21:24 UTC, dsanders11 commented
Closing as this was superseded by #1290.

2026-08-19 21:24 UTC, closed without merging